# Copyright 2021-present Intel Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
SAI PTFv2 Unit Tests for ACL Feature

Validates the SAI ACL implementation by:
  1. Discovering all SAI ACL APIs and attribute constants from
     test/saithriftv2/build/lib/sai_thrift (sai_adapter + sai_headers).
  2. Verifying that each CRUD API call with default values returns
     SAI_STATUS_SUCCESS.

ACL objects covered:
  - ACL Table Group         (create/get/remove)
  - ACL Table Group Member  (create/get/remove)
  - ACL Table               (create/get/remove)
  - ACL Entry               (create/get/set/remove)
  - ACL Counter             (create/get/set/remove)
  - ACL Range               (create/get/remove)

Prerequisites:
  Build the sai_thrift package before running these tests:
      export SAITHRIFTV2=y
      make saithrift-build        # from the repo root
  This produces test/saithriftv2/build/lib/sai_thrift which is installed
  into the Python environment by:
      cd test/saithriftv2 && python3 setup.py install

Run with:
    python3 -m pytest ptf/utest/sai_acl_unit_test.py -v
or:
    python3 -m unittest discover -s ptf/utest -p sai_acl_unit_test.py
"""

import inspect
import sys
import unittest

# All SAI API functions, type helpers, and attribute constants are imported
# directly from the generated sai_thrift package (no embedded stubs).  The package is produced
# by the saithriftv2 build and placed under
# test/saithriftv2/build/lib/sai_thrift.  If it is not installed this import
# will raise ImportError – build the package first (see module docstring).
from sai_thrift.sai_adapter import *  # noqa: F401,F403
from sai_thrift.sai_headers import *  # noqa: F401,F403
import sai_thrift.sai_adapter as adapter


# ---------------------------------------------------------------------------
# Helpers to introspect SAI ACL APIs and attributes at test time
# ---------------------------------------------------------------------------

def _get_acl_api_functions():
    """
    Return a sorted list of (name, callable) tuples for every ACL-related
    function exported by sai_thrift.sai_adapter.

    The naming convention used by gensairpc.pl is:
        sai_thrift_create_acl_*
        sai_thrift_remove_acl_*
        sai_thrift_set_acl_*_attribute
        sai_thrift_get_acl_*_attribute
    """
    import sai_thrift.sai_adapter as _mod
    return sorted(
        [
            (name, obj)
            for name, obj in inspect.getmembers(_mod, inspect.isfunction)
            if name.startswith("sai_thrift_") and "_acl_" in name
        ]
    )


def _get_acl_attribute_constants():
    """
    Return {name: value} for every ACL attribute constant visible in this
    module's global namespace after the wildcard imports above.

    Covers:
      SAI_ACL_TABLE_ATTR_*
      SAI_ACL_ENTRY_ATTR_*
      SAI_ACL_COUNTER_ATTR_*
      SAI_ACL_RANGE_ATTR_*
      SAI_ACL_TABLE_GROUP_ATTR_*
      SAI_ACL_TABLE_GROUP_MEMBER_ATTR_*
      SAI_ACL_TABLE_CHAIN_GROUP_ATTR_*
    """
    current_module = sys.modules[__name__]
    prefixes = (
        "SAI_ACL_TABLE_ATTR_",
        "SAI_ACL_ENTRY_ATTR_",
        "SAI_ACL_COUNTER_ATTR_",
        "SAI_ACL_RANGE_ATTR_",
        "SAI_ACL_TABLE_GROUP_ATTR_",
        "SAI_ACL_TABLE_GROUP_MEMBER_ATTR_",
        "SAI_ACL_TABLE_CHAIN_GROUP_ATTR_",
    )
    return {
        name: getattr(current_module, name)
        for name in dir(current_module)
        if any(name.startswith(p) for p in prefixes)
    }


# ---------------------------------------------------------------------------
# Mock Thrift client
#
# Intercepts every sai_thrift_* call that would normally go over the wire to
# the SAI RPC server.  Returns a distinct non-zero OID for create operations
# and SAI_STATUS_SUCCESS (0) for all other operations.
# ---------------------------------------------------------------------------

class _MockClient:
    """
    Simulates the SAI Thrift RPC server without requiring real hardware.

    Each method mirrors the Thrift client interface generated by the
    saithriftv2 build.  Return value conventions:
      - create_*  → non-zero object ID (OID)
      - remove_*  → 0 (SAI_STATUS_SUCCESS)
      - set_*     → 0 (SAI_STATUS_SUCCESS)
      - get_*     → attr_list with each attribute's value field populated
                    with a zero/default sai_thrift_attribute_value_t so that
                    the sai_adapter post-processing (attr.value.s32 etc.)
                    does not raise AttributeError.
    """

    _OID_TABLE_GROUP   = 0x0001000000000001
    _OID_CHAIN_GROUP   = 0x0001000000000002
    _OID_TABLE         = 0x0001000000000003
    _OID_ENTRY         = 0x0001000000000004
    _OID_COUNTER       = 0x0001000000000005
    _OID_RANGE         = 0x0001000000000006
    _OID_GROUP_MEMBER  = 0x0001000000000007

    @staticmethod
    def _populate_attr_list(attr_list):
        """
        For each attribute in attr_list, fill in a default
        sai_thrift_attribute_value_t so every numeric/bool/OID field is
        accessible without AttributeError.
        """
        if attr_list is None:
            return attr_list
        default_value = sai_thrift_attribute_value_t(
            s32=0, u8=0, u16=0, u32=0, u64=0,
            booldata=False, oid=0,
            objlist=sai_thrift_object_list_t(count=0, idlist=[]),
            s32list=sai_thrift_s32_list_t(count=0, int32list=[]),
        )
        for attr in attr_list.attr_list:
            if attr.value is None:
                attr.value = default_value
        return attr_list

    # ---- ACL Table Group ------------------------------------------------- #
    def sai_thrift_create_acl_table_group(self, thrift_acl_table_group=None):
        return self._OID_TABLE_GROUP

    def sai_thrift_remove_acl_table_group(self, acl_table_group_id):
        return 0

    def sai_thrift_set_acl_table_group_attribute(self, acl_table_group_id,
                                                 thrift_attr=None):
        return 0

    def sai_thrift_get_acl_table_group_attribute(self, acl_table_group_id,
                                                 thrift_attr_list=None):
        return self._populate_attr_list(thrift_attr_list)

    # ---- ACL Table Chain Group ------------------------------------------- #
    def sai_thrift_create_acl_table_chain_group(
            self, thrift_acl_table_chain_group=None):
        return self._OID_CHAIN_GROUP

    def sai_thrift_remove_acl_table_chain_group(
            self, acl_table_chain_group_id):
        return 0

    def sai_thrift_set_acl_table_chain_group_attribute(
            self, acl_table_chain_group_id, thrift_attr=None):
        return 0

    def sai_thrift_get_acl_table_chain_group_attribute(
            self, acl_table_chain_group_id, thrift_attr_list=None):
        return self._populate_attr_list(thrift_attr_list)

    # ---- ACL Table Group Member ------------------------------------------ #
    def sai_thrift_create_acl_table_group_member(
            self, thrift_acl_table_group_member=None):
        return self._OID_GROUP_MEMBER

    def sai_thrift_remove_acl_table_group_member(
            self, acl_table_group_member_id):
        return 0

    def sai_thrift_set_acl_table_group_member_attribute(
            self, acl_table_group_member_id, thrift_attr=None):
        return 0

    def sai_thrift_get_acl_table_group_member_attribute(
            self, acl_table_group_member_id, thrift_attr_list=None):
        return self._populate_attr_list(thrift_attr_list)

    # ---- ACL Table ------------------------------------------------------- #
    def sai_thrift_create_acl_table(self, thrift_acl_table=None):
        return self._OID_TABLE

    def sai_thrift_remove_acl_table(self, acl_table_id):
        return 0

    def sai_thrift_set_acl_table_attribute(self, acl_table_id,
                                           thrift_attr=None):
        return 0

    def sai_thrift_get_acl_table_attribute(self, acl_table_id,
                                           thrift_attr_list=None):
        return self._populate_attr_list(thrift_attr_list)

    # ---- ACL Entry ------------------------------------------------------- #
    def sai_thrift_create_acl_entry(self, thrift_acl_entry=None):
        return self._OID_ENTRY

    def sai_thrift_remove_acl_entry(self, acl_entry_id):
        return 0

    def sai_thrift_set_acl_entry_attribute(self, acl_entry_id,
                                           thrift_attr=None):
        return 0

    def sai_thrift_get_acl_entry_attribute(self, acl_entry_id,
                                           thrift_attr_list=None):
        return self._populate_attr_list(thrift_attr_list)

    # ---- ACL Counter ----------------------------------------------------- #
    def sai_thrift_create_acl_counter(self, thrift_acl_counter=None):
        return self._OID_COUNTER

    def sai_thrift_remove_acl_counter(self, acl_counter_id):
        return 0

    def sai_thrift_set_acl_counter_attribute(self, acl_counter_id,
                                             thrift_attr=None):
        return 0

    def sai_thrift_get_acl_counter_attribute(self, acl_counter_id,
                                             thrift_attr_list=None):
        return self._populate_attr_list(thrift_attr_list)

    # ---- ACL Range ------------------------------------------------------- #
    def sai_thrift_create_acl_range(self, thrift_acl_range=None):
        return self._OID_RANGE

    def sai_thrift_remove_acl_range(self, acl_range_id):
        return 0

    def sai_thrift_set_acl_range_attribute(self, acl_range_id,
                                           thrift_attr=None):
        return 0

    def sai_thrift_get_acl_range_attribute(self, acl_range_id,
                                           thrift_attr_list=None):
        return self._populate_attr_list(thrift_attr_list)


# ---------------------------------------------------------------------------
# Base class shared by all ACL unit-test classes
# ---------------------------------------------------------------------------

class SaiAclTestBase(unittest.TestCase):
    """
    Base class for SAI ACL unit tests.

    Attributes:
        client    – _MockClient instance (simulates the SAI RPC server)
        switch_id – placeholder switch OID
    """

    SAI_STATUS_SUCCESS = 0

    def setUp(self):
        super().setUp()
        self.client = _MockClient()
        self.switch_id = 0x2100000000

    def _assert_status_success(self, status, msg=""):
        self.assertEqual(
            status,
            self.SAI_STATUS_SUCCESS,
            msg or "Expected SAI_STATUS_SUCCESS (0), got {}".format(status),
        )

    def _assert_valid_oid(self, oid, msg=""):
        self.assertNotEqual(
            oid, 0,
            msg or "Expected a non-zero SAI object OID, got 0",
        )


# ===========================================================================
# Test Class 1: Discover ACL APIs and attributes from sai_thrift
# ===========================================================================

class TestAclApiDiscovery(SaiAclTestBase):
    """
    Verifies that sai_thrift exposes the expected set of SAI ACL API functions
    and attribute constants.

    All symbols are discovered at runtime from the installed sai_thrift package
    (test/saithriftv2/build/lib/sai_thrift) – no hard-coded fallback values.
    """

    EXPECTED_ACL_FUNCTIONS = [
        "sai_thrift_create_acl_table_group",
        "sai_thrift_remove_acl_table_group",
        "sai_thrift_set_acl_table_group_attribute",
        "sai_thrift_get_acl_table_group_attribute",
        "sai_thrift_create_acl_table_group_member",
        "sai_thrift_remove_acl_table_group_member",
        "sai_thrift_set_acl_table_group_member_attribute",
        "sai_thrift_get_acl_table_group_member_attribute",
        "sai_thrift_create_acl_table",
        "sai_thrift_remove_acl_table",
        "sai_thrift_set_acl_table_attribute",
        "sai_thrift_get_acl_table_attribute",
        "sai_thrift_create_acl_entry",
        "sai_thrift_remove_acl_entry",
        "sai_thrift_set_acl_entry_attribute",
        "sai_thrift_get_acl_entry_attribute",
        "sai_thrift_create_acl_counter",
        "sai_thrift_remove_acl_counter",
        "sai_thrift_set_acl_counter_attribute",
        "sai_thrift_get_acl_counter_attribute",
        "sai_thrift_create_acl_range",
        "sai_thrift_remove_acl_range",
        "sai_thrift_set_acl_range_attribute",
        "sai_thrift_get_acl_range_attribute",
    ]

    EXPECTED_ATTR_PREFIXES = [
        "SAI_ACL_TABLE_GROUP_ATTR_",
        "SAI_ACL_TABLE_GROUP_MEMBER_ATTR_",
        "SAI_ACL_TABLE_ATTR_",
        "SAI_ACL_ENTRY_ATTR_",
        "SAI_ACL_COUNTER_ATTR_",
        "SAI_ACL_RANGE_ATTR_",
    ]

    def test_acl_api_functions_discoverable(self):
        """
        All expected ACL CRUD functions must be present in sai_thrift.sai_adapter.
        """
        discovered = {name for name, _ in _get_acl_api_functions()}
        for func_name in self.EXPECTED_ACL_FUNCTIONS:
            self.assertIn(
                func_name,
                discovered,
                "ACL API function '{}' not found in sai_thrift.sai_adapter. "
                "Discovered ACL functions: {}".format(
                    func_name, sorted(discovered)
                ),
            )

    def test_acl_attribute_constants_discoverable(self):
        """
        At least one attribute constant must exist per expected prefix
        (sourced from sai_thrift.sai_headers).
        """
        constants = _get_acl_attribute_constants()
        for prefix in self.EXPECTED_ATTR_PREFIXES:
            matching = [k for k in constants if k.startswith(prefix)]
            self.assertTrue(
                len(matching) > 0,
                "No attribute constants with prefix '{}' found in "
                "sai_thrift.sai_headers. "
                "Available ACL constants: {}".format(
                    prefix, sorted(constants.keys())
                ),
            )

    def test_acl_table_group_attr_constants(self):
        """Core SAI_ACL_TABLE_GROUP_ATTR_* constants from sai_thrift.sai_headers."""
        required = [
            "SAI_ACL_TABLE_GROUP_ATTR_ACL_STAGE",
            "SAI_ACL_TABLE_GROUP_ATTR_ACL_BIND_POINT_TYPE_LIST",
            "SAI_ACL_TABLE_GROUP_ATTR_TYPE",
            "SAI_ACL_TABLE_GROUP_ATTR_MEMBER_LIST",
        ]
        constants = _get_acl_attribute_constants()
        for name in required:
            self.assertIn(name, constants,
                          "'{}' not found in sai_thrift.sai_headers".format(name))

    def test_acl_table_attr_mandatory_constants(self):
        """SAI_ACL_TABLE_ATTR_ACL_STAGE is present in sai_thrift.sai_headers."""
        constants = _get_acl_attribute_constants()
        self.assertIn("SAI_ACL_TABLE_ATTR_ACL_STAGE", constants)

    def test_acl_entry_attr_mandatory_constants(self):
        """SAI_ACL_ENTRY_ATTR_TABLE_ID is present in sai_thrift.sai_headers."""
        constants = _get_acl_attribute_constants()
        self.assertIn("SAI_ACL_ENTRY_ATTR_TABLE_ID", constants)

    def test_acl_counter_attr_constants(self):
        """Core SAI_ACL_COUNTER_ATTR_* constants from sai_thrift.sai_headers."""
        required = [
            "SAI_ACL_COUNTER_ATTR_TABLE_ID",
            "SAI_ACL_COUNTER_ATTR_ENABLE_PACKET_COUNT",
            "SAI_ACL_COUNTER_ATTR_ENABLE_BYTE_COUNT",
            "SAI_ACL_COUNTER_ATTR_PACKETS",
            "SAI_ACL_COUNTER_ATTR_BYTES",
        ]
        constants = _get_acl_attribute_constants()
        for name in required:
            self.assertIn(name, constants,
                          "'{}' not found in sai_thrift.sai_headers".format(name))

    def test_acl_range_attr_constants(self):
        """Core SAI_ACL_RANGE_ATTR_* constants from sai_thrift.sai_headers."""
        required = ["SAI_ACL_RANGE_ATTR_TYPE", "SAI_ACL_RANGE_ATTR_LIMIT"]
        constants = _get_acl_attribute_constants()
        for name in required:
            self.assertIn(name, constants,
                          "'{}' not found in sai_thrift.sai_headers".format(name))

    def test_acl_table_group_member_attr_constants(self):
        """Core SAI_ACL_TABLE_GROUP_MEMBER_ATTR_* constants from sai_thrift.sai_headers."""
        required = [
            "SAI_ACL_TABLE_GROUP_MEMBER_ATTR_ACL_TABLE_GROUP_ID",
            "SAI_ACL_TABLE_GROUP_MEMBER_ATTR_ACL_TABLE_ID",
            "SAI_ACL_TABLE_GROUP_MEMBER_ATTR_PRIORITY",
        ]
        constants = _get_acl_attribute_constants()
        for name in required:
            self.assertIn(name, constants,
                          "'{}' not found in sai_thrift.sai_headers".format(name))

    def test_acl_api_function_count(self):
        """
        sai_thrift.sai_adapter must export at least 24 ACL functions
        (6 object types x 4 CRUD operations).
        """
        discovered = _get_acl_api_functions()
        self.assertGreaterEqual(
            len(discovered),
            24,
            "Expected at least 24 ACL API functions in sai_thrift.sai_adapter, "
            "found {}".format(len(discovered)),
        )


# ===========================================================================
# Test Class 2: ACL Table Group CRUD
# ===========================================================================

class TestAclTableGroupCrud(SaiAclTestBase):
    """
    Validates Create / Get / Remove for ACL Table Group using the sai_thrift
    adapter functions and attribute constants.

    SAI_ACL_TABLE_GROUP_ATTR_ACL_STAGE is MANDATORY_ON_CREATE.
    """

    def test_create_acl_table_group_ingress_default(self):
        """
        CREATE – ingress ACL table group with default attributes.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_table_group = sai_thrift_create_acl_table_group(
            self.client,
            acl_stage=SAI_ACL_STAGE_INGRESS,
        )
        self._assert_valid_oid(acl_table_group)
        self._assert_status_success(adapter.status)

    def test_create_acl_table_group_egress_parallel(self):
        """
        CREATE – egress ACL table group, parallel type, PORT bind point.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        bp_list = sai_thrift_s32_list_t(
            count=1, int32list=[SAI_ACL_BIND_POINT_TYPE_PORT]
        )
        acl_table_group = sai_thrift_create_acl_table_group(
            self.client,
            acl_stage=SAI_ACL_STAGE_EGRESS,
            acl_bind_point_type_list=bp_list,
            type=SAI_ACL_TABLE_GROUP_TYPE_PARALLEL,
        )
        self._assert_valid_oid(acl_table_group)
        self._assert_status_success(adapter.status)

    def test_create_acl_table_group_sequential_port_lag(self):
        """
        CREATE – ingress ACL table group, sequential type, PORT+LAG bind points.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        bp_list = sai_thrift_s32_list_t(
            count=2,
            int32list=[SAI_ACL_BIND_POINT_TYPE_PORT, SAI_ACL_BIND_POINT_TYPE_LAG],
        )
        acl_table_group = sai_thrift_create_acl_table_group(
            self.client,
            acl_stage=SAI_ACL_STAGE_INGRESS,
            acl_bind_point_type_list=bp_list,
            type=SAI_ACL_TABLE_GROUP_TYPE_SEQUENTIAL,
        )
        self._assert_valid_oid(acl_table_group)
        self._assert_status_success(adapter.status)

    def test_get_acl_table_group_attribute(self):
        """
        GET – read ACL stage attribute back from an ACL table group.
        Expected: SAI_STATUS_SUCCESS, non-None result.
        """
        acl_table_group = sai_thrift_create_acl_table_group(
            self.client, acl_stage=SAI_ACL_STAGE_INGRESS
        )
        self._assert_valid_oid(acl_table_group)

        attr = sai_thrift_get_acl_table_group_attribute(
            self.client, acl_table_group, acl_stage=True
        )
        self._assert_status_success(adapter.status)
        self.assertIsNotNone(attr)

    def test_remove_acl_table_group(self):
        """
        REMOVE – delete an ACL table group.
        Expected: SAI_STATUS_SUCCESS.
        """
        acl_table_group = sai_thrift_create_acl_table_group(
            self.client, acl_stage=SAI_ACL_STAGE_INGRESS
        )
        self._assert_valid_oid(acl_table_group)

        status = sai_thrift_remove_acl_table_group(self.client, acl_table_group)
        self._assert_status_success(status)

    def test_crud_acl_table_group_lifecycle(self):
        """
        Full lifecycle: create → get → remove.
        All operations must return SAI_STATUS_SUCCESS.
        """
        acl_table_group = sai_thrift_create_acl_table_group(
            self.client, acl_stage=SAI_ACL_STAGE_INGRESS
        )
        self._assert_valid_oid(acl_table_group)
        self._assert_status_success(adapter.status, "create")

        attr = sai_thrift_get_acl_table_group_attribute(
            self.client, acl_table_group, acl_stage=True
        )
        self._assert_status_success(adapter.status, "get")
        self.assertIsNotNone(attr)

        status = sai_thrift_remove_acl_table_group(self.client, acl_table_group)
        self._assert_status_success(status, "remove")


# ===========================================================================
# Test Class 3: ACL Table CRUD
# ===========================================================================

class TestAclTableCrud(SaiAclTestBase):
    """
    Validates Create / Get / Remove for ACL Table using the sai_thrift adapter
    functions and attribute constants.

    SAI_ACL_TABLE_ATTR_ACL_STAGE is MANDATORY_ON_CREATE; at least one match
    field must be enabled.
    """

    def test_create_acl_table_ingress_src_ip(self):
        """
        CREATE – minimal ingress ACL table with src_ip match field.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_table = sai_thrift_create_acl_table(
            self.client,
            acl_stage=SAI_ACL_STAGE_INGRESS,
            field_src_ip=True,
        )
        self._assert_valid_oid(acl_table)
        self._assert_status_success(adapter.status)

    def test_create_acl_table_egress_multiple_fields(self):
        """
        CREATE – egress ACL table with dst_ip, protocol, and L4 port fields.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_table = sai_thrift_create_acl_table(
            self.client,
            acl_stage=SAI_ACL_STAGE_EGRESS,
            field_dst_ip=True,
            field_ip_protocol=True,
            field_l4_src_port=True,
            field_l4_dst_port=True,
        )
        self._assert_valid_oid(acl_table)
        self._assert_status_success(adapter.status)

    def test_create_acl_table_with_port_vlan_bind_point(self):
        """
        CREATE – ACL table bound to PORT and VLAN bind points.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        bp_list = sai_thrift_s32_list_t(
            count=2,
            int32list=[SAI_ACL_BIND_POINT_TYPE_PORT, SAI_ACL_BIND_POINT_TYPE_VLAN],
        )
        acl_table = sai_thrift_create_acl_table(
            self.client,
            acl_stage=SAI_ACL_STAGE_INGRESS,
            acl_bind_point_type_list=bp_list,
            field_src_ip=True,
        )
        self._assert_valid_oid(acl_table)
        self._assert_status_success(adapter.status)

    def test_create_acl_table_mac_fields(self):
        """
        CREATE – L2 ACL table with src/dst MAC match fields.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_table = sai_thrift_create_acl_table(
            self.client,
            acl_stage=SAI_ACL_STAGE_INGRESS,
            field_src_mac=True,
            field_dst_mac=True,
        )
        self._assert_valid_oid(acl_table)
        self._assert_status_success(adapter.status)

    def test_create_acl_table_ipv6_field(self):
        """
        CREATE – ACL table with IPv6 src address match field.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_table = sai_thrift_create_acl_table(
            self.client,
            acl_stage=SAI_ACL_STAGE_INGRESS,
            field_src_ipv6=True,
        )
        self._assert_valid_oid(acl_table)
        self._assert_status_success(adapter.status)

    def test_get_acl_table_attribute(self):
        """
        GET – read ACL stage attribute from an ACL table.
        Expected: SAI_STATUS_SUCCESS, non-None result.
        """
        acl_table = sai_thrift_create_acl_table(
            self.client, acl_stage=SAI_ACL_STAGE_INGRESS, field_src_ip=True
        )
        self._assert_valid_oid(acl_table)

        attr = sai_thrift_get_acl_table_attribute(
            self.client, acl_table, acl_stage=True
        )
        self._assert_status_success(adapter.status)
        self.assertIsNotNone(attr)

    def test_remove_acl_table(self):
        """
        REMOVE – delete an ACL table.
        Expected: SAI_STATUS_SUCCESS.
        """
        acl_table = sai_thrift_create_acl_table(
            self.client, acl_stage=SAI_ACL_STAGE_INGRESS, field_src_ip=True
        )
        self._assert_valid_oid(acl_table)

        status = sai_thrift_remove_acl_table(self.client, acl_table)
        self._assert_status_success(status)

    def test_crud_acl_table_lifecycle(self):
        """
        Full lifecycle: create → get → remove.
        """
        acl_table = sai_thrift_create_acl_table(
            self.client, acl_stage=SAI_ACL_STAGE_INGRESS, field_src_ip=True
        )
        self._assert_valid_oid(acl_table)
        self._assert_status_success(adapter.status, "create")

        attr = sai_thrift_get_acl_table_attribute(
            self.client, acl_table, acl_stage=True
        )
        self._assert_status_success(adapter.status, "get")
        self.assertIsNotNone(attr)

        status = sai_thrift_remove_acl_table(self.client, acl_table)
        self._assert_status_success(status, "remove")


# ===========================================================================
# Test Class 4: ACL Table Group Member CRUD
# ===========================================================================

class TestAclTableGroupMemberCrud(SaiAclTestBase):
    """
    Validates Create / Get / Remove for ACL Table Group Member.

    All three MANDATORY_ON_CREATE attributes are supplied:
      SAI_ACL_TABLE_GROUP_MEMBER_ATTR_ACL_TABLE_GROUP_ID
      SAI_ACL_TABLE_GROUP_MEMBER_ATTR_ACL_TABLE_ID
      SAI_ACL_TABLE_GROUP_MEMBER_ATTR_PRIORITY
    """

    def setUp(self):
        super().setUp()
        self.acl_table_group = sai_thrift_create_acl_table_group(
            self.client, acl_stage=SAI_ACL_STAGE_INGRESS
        )
        self.acl_table = sai_thrift_create_acl_table(
            self.client, acl_stage=SAI_ACL_STAGE_INGRESS, field_src_ip=True
        )

    def tearDown(self):
        sai_thrift_remove_acl_table(self.client, self.acl_table)
        sai_thrift_remove_acl_table_group(self.client, self.acl_table_group)
        super().tearDown()

    def test_create_acl_table_group_member_priority_10(self):
        """
        CREATE – ACL table group member with priority 10.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        member = sai_thrift_create_acl_table_group_member(
            self.client,
            acl_table_group_id=self.acl_table_group,
            acl_table_id=self.acl_table,
            priority=10,
        )
        self._assert_valid_oid(member)
        self._assert_status_success(adapter.status)
        sai_thrift_remove_acl_table_group_member(self.client, member)

    def test_create_acl_table_group_member_priority_100(self):
        """
        CREATE – ACL table group member with priority 100.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        member = sai_thrift_create_acl_table_group_member(
            self.client,
            acl_table_group_id=self.acl_table_group,
            acl_table_id=self.acl_table,
            priority=100,
        )
        self._assert_valid_oid(member)
        self._assert_status_success(adapter.status)
        sai_thrift_remove_acl_table_group_member(self.client, member)

    def test_get_acl_table_group_member_attribute(self):
        """
        GET – read priority from an ACL table group member.
        Expected: SAI_STATUS_SUCCESS, non-None result.
        """
        member = sai_thrift_create_acl_table_group_member(
            self.client,
            acl_table_group_id=self.acl_table_group,
            acl_table_id=self.acl_table,
            priority=10,
        )
        self._assert_valid_oid(member)

        attr = sai_thrift_get_acl_table_group_member_attribute(
            self.client, member, priority=True
        )
        self._assert_status_success(adapter.status)
        self.assertIsNotNone(attr)
        sai_thrift_remove_acl_table_group_member(self.client, member)

    def test_remove_acl_table_group_member(self):
        """
        REMOVE – delete an ACL table group member.
        Expected: SAI_STATUS_SUCCESS.
        """
        member = sai_thrift_create_acl_table_group_member(
            self.client,
            acl_table_group_id=self.acl_table_group,
            acl_table_id=self.acl_table,
            priority=10,
        )
        self._assert_valid_oid(member)

        status = sai_thrift_remove_acl_table_group_member(self.client, member)
        self._assert_status_success(status)

    def test_crud_acl_table_group_member_lifecycle(self):
        """
        Full lifecycle: create → get → remove.
        """
        member = sai_thrift_create_acl_table_group_member(
            self.client,
            acl_table_group_id=self.acl_table_group,
            acl_table_id=self.acl_table,
            priority=20,
        )
        self._assert_valid_oid(member)
        self._assert_status_success(adapter.status, "create")

        attr = sai_thrift_get_acl_table_group_member_attribute(
            self.client, member, priority=True
        )
        self._assert_status_success(adapter.status, "get")
        self.assertIsNotNone(attr)

        status = sai_thrift_remove_acl_table_group_member(self.client, member)
        self._assert_status_success(status, "remove")


# ===========================================================================
# Test Class 5: ACL Entry CRUD
# ===========================================================================

class TestAclEntryCrud(SaiAclTestBase):
    """
    Validates Create / Get / Set / Remove for ACL Entry.

    SAI_ACL_ENTRY_ATTR_TABLE_ID is MANDATORY_ON_CREATE.
    The ACL table is pre-created in setUp and removed in tearDown.
    """

    def setUp(self):
        super().setUp()
        self.acl_table = sai_thrift_create_acl_table(
            self.client, acl_stage=SAI_ACL_STAGE_INGRESS, field_src_ip=True
        )

    def tearDown(self):
        sai_thrift_remove_acl_table(self.client, self.acl_table)
        super().tearDown()

    def _make_src_ip_field(self, ip="10.0.0.1", mask="255.255.255.255"):
        return sai_thrift_acl_field_data_t(
            enable=True,
            data=sai_thrift_acl_field_data_data_t(ip4=ip),
            mask=sai_thrift_acl_field_data_mask_t(ip4=mask),
        )

    def _make_packet_action(self, action=None):
        if action is None:
            action = SAI_PACKET_ACTION_DROP
        return sai_thrift_acl_action_data_t(
            enable=True,
            parameter=sai_thrift_acl_action_parameter_t(s32=action),
        )

    def test_create_acl_entry_drop_action(self):
        """
        CREATE – entry with DROP packet action.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_entry = sai_thrift_create_acl_entry(
            self.client,
            table_id=self.acl_table,
            priority=10,
            field_src_ip=self._make_src_ip_field(),
            action_packet_action=self._make_packet_action(SAI_PACKET_ACTION_DROP),
        )
        self._assert_valid_oid(acl_entry)
        self._assert_status_success(adapter.status)
        sai_thrift_remove_acl_entry(self.client, acl_entry)

    def test_create_acl_entry_forward_action(self):
        """
        CREATE – entry with FORWARD packet action.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_entry = sai_thrift_create_acl_entry(
            self.client,
            table_id=self.acl_table,
            priority=5,
            field_src_ip=self._make_src_ip_field("192.168.1.0", "255.255.255.0"),
            action_packet_action=self._make_packet_action(SAI_PACKET_ACTION_FORWARD),
        )
        self._assert_valid_oid(acl_entry)
        self._assert_status_success(adapter.status)
        sai_thrift_remove_acl_entry(self.client, acl_entry)

    def test_create_acl_entry_trap_action(self):
        """
        CREATE – entry with TRAP (copy to CPU) packet action.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_entry = sai_thrift_create_acl_entry(
            self.client,
            table_id=self.acl_table,
            priority=15,
            field_src_ip=self._make_src_ip_field("10.1.0.0", "255.255.0.0"),
            action_packet_action=self._make_packet_action(SAI_PACKET_ACTION_TRAP),
        )
        self._assert_valid_oid(acl_entry)
        self._assert_status_success(adapter.status)
        sai_thrift_remove_acl_entry(self.client, acl_entry)

    def test_get_acl_entry_attribute(self):
        """
        GET – read admin_state and priority from an ACL entry.
        Expected: SAI_STATUS_SUCCESS, non-None result.
        """
        acl_entry = sai_thrift_create_acl_entry(
            self.client,
            table_id=self.acl_table,
            priority=10,
            field_src_ip=self._make_src_ip_field(),
            action_packet_action=self._make_packet_action(),
        )
        self._assert_valid_oid(acl_entry)

        attr = sai_thrift_get_acl_entry_attribute(
            self.client, acl_entry, admin_state=True, priority=True
        )
        self._assert_status_success(adapter.status)
        self.assertIsNotNone(attr)
        sai_thrift_remove_acl_entry(self.client, acl_entry)

    def test_set_acl_entry_attribute_priority(self):
        """
        SET – update priority of an ACL entry.
        Expected: SAI_STATUS_SUCCESS.
        """
        acl_entry = sai_thrift_create_acl_entry(
            self.client,
            table_id=self.acl_table,
            priority=10,
            field_src_ip=self._make_src_ip_field(),
            action_packet_action=self._make_packet_action(),
        )
        self._assert_valid_oid(acl_entry)

        status = sai_thrift_set_acl_entry_attribute(
            self.client, acl_entry, priority=20
        )
        self._assert_status_success(status)
        sai_thrift_remove_acl_entry(self.client, acl_entry)

    def test_set_acl_entry_attribute_admin_state(self):
        """
        SET – disable and re-enable an ACL entry via admin_state.
        Expected: SAI_STATUS_SUCCESS for both set calls.
        """
        acl_entry = sai_thrift_create_acl_entry(
            self.client,
            table_id=self.acl_table,
            priority=10,
            field_src_ip=self._make_src_ip_field(),
            action_packet_action=self._make_packet_action(),
        )
        self._assert_valid_oid(acl_entry)

        status = sai_thrift_set_acl_entry_attribute(
            self.client, acl_entry, admin_state=False
        )
        self._assert_status_success(status, "disable")

        status = sai_thrift_set_acl_entry_attribute(
            self.client, acl_entry, admin_state=True
        )
        self._assert_status_success(status, "re-enable")
        sai_thrift_remove_acl_entry(self.client, acl_entry)

    def test_remove_acl_entry(self):
        """
        REMOVE – delete an ACL entry.
        Expected: SAI_STATUS_SUCCESS.
        """
        acl_entry = sai_thrift_create_acl_entry(
            self.client,
            table_id=self.acl_table,
            priority=10,
            field_src_ip=self._make_src_ip_field("172.16.0.1"),
            action_packet_action=self._make_packet_action(),
        )
        self._assert_valid_oid(acl_entry)

        status = sai_thrift_remove_acl_entry(self.client, acl_entry)
        self._assert_status_success(status)

    def test_crud_acl_entry_lifecycle(self):
        """
        Full lifecycle: create → get → set → remove.
        """
        acl_entry = sai_thrift_create_acl_entry(
            self.client,
            table_id=self.acl_table,
            priority=10,
            field_src_ip=self._make_src_ip_field("10.10.10.1"),
            action_packet_action=self._make_packet_action(),
        )
        self._assert_valid_oid(acl_entry)
        self._assert_status_success(adapter.status, "create")

        attr = sai_thrift_get_acl_entry_attribute(
            self.client, acl_entry, priority=True
        )
        self._assert_status_success(adapter.status, "get")
        self.assertIsNotNone(attr)

        status = sai_thrift_set_acl_entry_attribute(
            self.client, acl_entry, admin_state=True
        )
        self._assert_status_success(status, "set")

        status = sai_thrift_remove_acl_entry(self.client, acl_entry)
        self._assert_status_success(status, "remove")


# ===========================================================================
# Test Class 6: ACL Counter CRUD
# ===========================================================================

class TestAclCounterCrud(SaiAclTestBase):
    """
    Validates Create / Get / Set / Remove for ACL Counter.

    SAI_ACL_COUNTER_ATTR_TABLE_ID is MANDATORY_ON_CREATE.
    An ACL table and an ACL entry are pre-created in setUp.
    """

    def setUp(self):
        super().setUp()
        self.acl_table = sai_thrift_create_acl_table(
            self.client, acl_stage=SAI_ACL_STAGE_INGRESS, field_src_ip=True
        )
        self.acl_entry = sai_thrift_create_acl_entry(
            self.client,
            table_id=self.acl_table,
            priority=10,
            field_src_ip=sai_thrift_acl_field_data_t(
                enable=True,
                data=sai_thrift_acl_field_data_data_t(ip4="10.0.0.1"),
                mask=sai_thrift_acl_field_data_mask_t(ip4="255.255.255.255"),
            ),
            action_packet_action=sai_thrift_acl_action_data_t(
                enable=True,
                parameter=sai_thrift_acl_action_parameter_t(
                    s32=SAI_PACKET_ACTION_DROP
                ),
            ),
        )

    def tearDown(self):
        sai_thrift_remove_acl_entry(self.client, self.acl_entry)
        sai_thrift_remove_acl_table(self.client, self.acl_table)
        super().tearDown()

    def test_create_acl_counter_byte_default(self):
        """
        CREATE – byte counter (default, no explicit enable flags).
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_counter = sai_thrift_create_acl_counter(
            self.client, table_id=self.acl_table
        )
        self._assert_valid_oid(acl_counter)
        self._assert_status_success(adapter.status)
        sai_thrift_remove_acl_counter(self.client, acl_counter)

    def test_create_acl_counter_packet_count(self):
        """
        CREATE – counter with packet counting enabled.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_counter = sai_thrift_create_acl_counter(
            self.client, table_id=self.acl_table, enable_packet_count=True
        )
        self._assert_valid_oid(acl_counter)
        self._assert_status_success(adapter.status)
        sai_thrift_remove_acl_counter(self.client, acl_counter)

    def test_create_acl_counter_byte_count(self):
        """
        CREATE – counter with byte counting enabled.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_counter = sai_thrift_create_acl_counter(
            self.client, table_id=self.acl_table, enable_byte_count=True
        )
        self._assert_valid_oid(acl_counter)
        self._assert_status_success(adapter.status)
        sai_thrift_remove_acl_counter(self.client, acl_counter)

    def test_create_acl_counter_packet_and_byte(self):
        """
        CREATE – counter with both packet and byte counting enabled.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_counter = sai_thrift_create_acl_counter(
            self.client,
            table_id=self.acl_table,
            enable_packet_count=True,
            enable_byte_count=True,
        )
        self._assert_valid_oid(acl_counter)
        self._assert_status_success(adapter.status)
        sai_thrift_remove_acl_counter(self.client, acl_counter)

    def test_get_acl_counter_attribute_packets(self):
        """
        GET – read packet count attribute.
        Expected: SAI_STATUS_SUCCESS, non-None result.
        """
        acl_counter = sai_thrift_create_acl_counter(
            self.client, table_id=self.acl_table, enable_packet_count=True
        )
        self._assert_valid_oid(acl_counter)

        attr = sai_thrift_get_acl_counter_attribute(
            self.client, acl_counter, packets=True
        )
        self._assert_status_success(adapter.status)
        self.assertIsNotNone(attr)
        sai_thrift_remove_acl_counter(self.client, acl_counter)

    def test_get_acl_counter_attribute_bytes(self):
        """
        GET – read byte count attribute.
        Expected: SAI_STATUS_SUCCESS, non-None result.
        """
        acl_counter = sai_thrift_create_acl_counter(
            self.client, table_id=self.acl_table, enable_byte_count=True
        )
        self._assert_valid_oid(acl_counter)

        attr = sai_thrift_get_acl_counter_attribute(
            self.client, acl_counter, bytes=True
        )
        self._assert_status_success(adapter.status)
        self.assertIsNotNone(attr)
        sai_thrift_remove_acl_counter(self.client, acl_counter)

    def test_set_acl_counter_attribute_reset_packets(self):
        """
        SET – reset packet counter to 0.
        Expected: SAI_STATUS_SUCCESS.
        """
        acl_counter = sai_thrift_create_acl_counter(
            self.client, table_id=self.acl_table, enable_packet_count=True
        )
        self._assert_valid_oid(acl_counter)

        status = sai_thrift_set_acl_counter_attribute(
            self.client, acl_counter, packets=0
        )
        self._assert_status_success(status)
        sai_thrift_remove_acl_counter(self.client, acl_counter)

    def test_set_acl_counter_attribute_reset_bytes(self):
        """
        SET – reset byte counter to 0.
        Expected: SAI_STATUS_SUCCESS.
        """
        acl_counter = sai_thrift_create_acl_counter(
            self.client, table_id=self.acl_table, enable_byte_count=True
        )
        self._assert_valid_oid(acl_counter)

        status = sai_thrift_set_acl_counter_attribute(
            self.client, acl_counter, bytes=0
        )
        self._assert_status_success(status)
        sai_thrift_remove_acl_counter(self.client, acl_counter)

    def test_attach_detach_acl_counter_to_entry(self):
        """
        SET – attach an ACL counter to an entry then detach it.
        Expected: both set calls return SAI_STATUS_SUCCESS.
        """
        acl_counter = sai_thrift_create_acl_counter(
            self.client, table_id=self.acl_table, enable_packet_count=True
        )
        self._assert_valid_oid(acl_counter)

        action_counter = sai_thrift_acl_action_data_t(
            enable=True,
            parameter=sai_thrift_acl_action_parameter_t(oid=acl_counter),
        )
        status = sai_thrift_set_acl_entry_attribute(
            self.client, self.acl_entry, action_counter=action_counter
        )
        self._assert_status_success(status, "attach")

        detach = sai_thrift_acl_action_data_t(
            enable=False,
            parameter=sai_thrift_acl_action_parameter_t(oid=0),
        )
        status = sai_thrift_set_acl_entry_attribute(
            self.client, self.acl_entry, action_counter=detach
        )
        self._assert_status_success(status, "detach")
        sai_thrift_remove_acl_counter(self.client, acl_counter)

    def test_remove_acl_counter(self):
        """
        REMOVE – delete an ACL counter.
        Expected: SAI_STATUS_SUCCESS.
        """
        acl_counter = sai_thrift_create_acl_counter(
            self.client, table_id=self.acl_table
        )
        self._assert_valid_oid(acl_counter)

        status = sai_thrift_remove_acl_counter(self.client, acl_counter)
        self._assert_status_success(status)

    def test_crud_acl_counter_lifecycle(self):
        """
        Full lifecycle: create → get → set → remove.
        """
        acl_counter = sai_thrift_create_acl_counter(
            self.client,
            table_id=self.acl_table,
            enable_packet_count=True,
            enable_byte_count=True,
        )
        self._assert_valid_oid(acl_counter)
        self._assert_status_success(adapter.status, "create")

        attr = sai_thrift_get_acl_counter_attribute(
            self.client, acl_counter, packets=True
        )
        self._assert_status_success(adapter.status, "get")
        self.assertIsNotNone(attr)

        status = sai_thrift_set_acl_counter_attribute(
            self.client, acl_counter, packets=0
        )
        self._assert_status_success(status, "set")

        status = sai_thrift_remove_acl_counter(self.client, acl_counter)
        self._assert_status_success(status, "remove")


# ===========================================================================
# Test Class 7: ACL Range CRUD
# ===========================================================================

class TestAclRangeCrud(SaiAclTestBase):
    """
    Validates Create / Get / Remove for ACL Range.

    SAI_ACL_RANGE_ATTR_TYPE and SAI_ACL_RANGE_ATTR_LIMIT are both
    MANDATORY_ON_CREATE.
    """

    def test_create_acl_range_l4_src_port(self):
        """
        CREATE – L4 source port range 1024–65535.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_range = sai_thrift_create_acl_range(
            self.client,
            type=SAI_ACL_RANGE_TYPE_L4_SRC_PORT_RANGE,
            limit=sai_thrift_u32_range_t(min=1024, max=65535),
        )
        self._assert_valid_oid(acl_range)
        self._assert_status_success(adapter.status)
        sai_thrift_remove_acl_range(self.client, acl_range)

    def test_create_acl_range_l4_dst_port(self):
        """
        CREATE – L4 destination port range 80–443.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_range = sai_thrift_create_acl_range(
            self.client,
            type=SAI_ACL_RANGE_TYPE_L4_DST_PORT_RANGE,
            limit=sai_thrift_u32_range_t(min=80, max=443),
        )
        self._assert_valid_oid(acl_range)
        self._assert_status_success(adapter.status)
        sai_thrift_remove_acl_range(self.client, acl_range)

    def test_create_acl_range_outer_vlan(self):
        """
        CREATE – outer VLAN range 100–200.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_range = sai_thrift_create_acl_range(
            self.client,
            type=SAI_ACL_RANGE_TYPE_OUTER_VLAN,
            limit=sai_thrift_u32_range_t(min=100, max=200),
        )
        self._assert_valid_oid(acl_range)
        self._assert_status_success(adapter.status)
        sai_thrift_remove_acl_range(self.client, acl_range)

    def test_create_acl_range_inner_vlan(self):
        """
        CREATE – inner VLAN range 1–4094.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_range = sai_thrift_create_acl_range(
            self.client,
            type=SAI_ACL_RANGE_TYPE_INNER_VLAN,
            limit=sai_thrift_u32_range_t(min=1, max=4094),
        )
        self._assert_valid_oid(acl_range)
        self._assert_status_success(adapter.status)
        sai_thrift_remove_acl_range(self.client, acl_range)

    def test_create_acl_range_packet_length(self):
        """
        CREATE – packet length range 64–1500 bytes.
        Expected: non-zero OID, SAI_STATUS_SUCCESS.
        """
        acl_range = sai_thrift_create_acl_range(
            self.client,
            type=SAI_ACL_RANGE_TYPE_PACKET_LENGTH,
            limit=sai_thrift_u32_range_t(min=64, max=1500),
        )
        self._assert_valid_oid(acl_range)
        self._assert_status_success(adapter.status)
        sai_thrift_remove_acl_range(self.client, acl_range)

    def test_get_acl_range_attribute(self):
        """
        GET – read range type attribute.
        Expected: SAI_STATUS_SUCCESS, non-None result.
        """
        acl_range = sai_thrift_create_acl_range(
            self.client,
            type=SAI_ACL_RANGE_TYPE_L4_SRC_PORT_RANGE,
            limit=sai_thrift_u32_range_t(min=1024, max=65535),
        )
        self._assert_valid_oid(acl_range)

        attr = sai_thrift_get_acl_range_attribute(
            self.client, acl_range, type=True
        )
        self._assert_status_success(adapter.status)
        self.assertIsNotNone(attr)
        sai_thrift_remove_acl_range(self.client, acl_range)

    def test_remove_acl_range(self):
        """
        REMOVE – delete an ACL range.
        Expected: SAI_STATUS_SUCCESS.
        """
        acl_range = sai_thrift_create_acl_range(
            self.client,
            type=SAI_ACL_RANGE_TYPE_L4_DST_PORT_RANGE,
            limit=sai_thrift_u32_range_t(min=0, max=1023),
        )
        self._assert_valid_oid(acl_range)

        status = sai_thrift_remove_acl_range(self.client, acl_range)
        self._assert_status_success(status)

    def test_crud_acl_range_lifecycle(self):
        """
        Full lifecycle: create → get → remove.
        """
        acl_range = sai_thrift_create_acl_range(
            self.client,
            type=SAI_ACL_RANGE_TYPE_L4_DST_PORT_RANGE,
            limit=sai_thrift_u32_range_t(min=8080, max=8090),
        )
        self._assert_valid_oid(acl_range)
        self._assert_status_success(adapter.status, "create")

        attr = sai_thrift_get_acl_range_attribute(
            self.client, acl_range, type=True
        )
        self._assert_status_success(adapter.status, "get")
        self.assertIsNotNone(attr)

        status = sai_thrift_remove_acl_range(self.client, acl_range)
        self._assert_status_success(status, "remove")


# ===========================================================================
# Test Class 8: Full ACL pipeline integration
# ===========================================================================

class TestAclPipelineIntegration(SaiAclTestBase):
    """
    Exercises the complete ACL pipeline using the mock Thrift client:

        ACL Table Group
            └── ACL Table Group Member
                    └── ACL Table
                            ├── ACL Entry
                            └── ACL Counter (attached to the entry)

    Covers both ingress and egress paths and a range-based pipeline.
    All operations must return SAI_STATUS_SUCCESS.
    """

    def test_full_acl_pipeline_ingress(self):
        """
        Build and teardown a complete ingress ACL pipeline:
          create group → create table → create member → create entry →
          create counter → attach counter → get counter → detach → teardown.
        """
        bp_list = sai_thrift_s32_list_t(
            count=2,
            int32list=[SAI_ACL_BIND_POINT_TYPE_PORT, SAI_ACL_BIND_POINT_TYPE_LAG],
        )

        acl_table_group = sai_thrift_create_acl_table_group(
            self.client,
            acl_stage=SAI_ACL_STAGE_INGRESS,
            acl_bind_point_type_list=bp_list,
            type=SAI_ACL_TABLE_GROUP_TYPE_PARALLEL,
        )
        self._assert_valid_oid(acl_table_group, "create group")
        self._assert_status_success(adapter.status)

        acl_table = sai_thrift_create_acl_table(
            self.client,
            acl_stage=SAI_ACL_STAGE_INGRESS,
            acl_bind_point_type_list=bp_list,
            field_src_ip=True,
        )
        self._assert_valid_oid(acl_table, "create table")
        self._assert_status_success(adapter.status)

        member = sai_thrift_create_acl_table_group_member(
            self.client,
            acl_table_group_id=acl_table_group,
            acl_table_id=acl_table,
            priority=10,
        )
        self._assert_valid_oid(member, "create member")
        self._assert_status_success(adapter.status)

        acl_entry = sai_thrift_create_acl_entry(
            self.client,
            table_id=acl_table,
            priority=10,
            field_src_ip=sai_thrift_acl_field_data_t(
                enable=True,
                data=sai_thrift_acl_field_data_data_t(ip4="10.0.0.1"),
                mask=sai_thrift_acl_field_data_mask_t(ip4="255.255.255.255"),
            ),
            action_packet_action=sai_thrift_acl_action_data_t(
                enable=True,
                parameter=sai_thrift_acl_action_parameter_t(
                    s32=SAI_PACKET_ACTION_DROP
                ),
            ),
        )
        self._assert_valid_oid(acl_entry, "create entry")
        self._assert_status_success(adapter.status)

        acl_counter = sai_thrift_create_acl_counter(
            self.client, table_id=acl_table, enable_packet_count=True
        )
        self._assert_valid_oid(acl_counter, "create counter")
        self._assert_status_success(adapter.status)

        status = sai_thrift_set_acl_entry_attribute(
            self.client,
            acl_entry,
            action_counter=sai_thrift_acl_action_data_t(
                enable=True,
                parameter=sai_thrift_acl_action_parameter_t(oid=acl_counter),
            ),
        )
        self._assert_status_success(status, "attach counter")

        attr = sai_thrift_get_acl_counter_attribute(
            self.client, acl_counter, packets=True
        )
        self._assert_status_success(adapter.status, "get counter")
        self.assertIsNotNone(attr)

        sai_thrift_set_acl_entry_attribute(
            self.client,
            acl_entry,
            action_counter=sai_thrift_acl_action_data_t(
                enable=False,
                parameter=sai_thrift_acl_action_parameter_t(oid=0),
            ),
        )

        self._assert_status_success(
            sai_thrift_remove_acl_counter(self.client, acl_counter), "remove counter")
        self._assert_status_success(
            sai_thrift_remove_acl_entry(self.client, acl_entry), "remove entry")
        self._assert_status_success(
            sai_thrift_remove_acl_table_group_member(self.client, member), "remove member")
        self._assert_status_success(
            sai_thrift_remove_acl_table(self.client, acl_table), "remove table")
        self._assert_status_success(
            sai_thrift_remove_acl_table_group(self.client, acl_table_group), "remove group")

    def test_full_acl_pipeline_egress(self):
        """
        Build and teardown a complete egress ACL pipeline with DST IP filter.
        """
        bp_list = sai_thrift_s32_list_t(
            count=1, int32list=[SAI_ACL_BIND_POINT_TYPE_PORT]
        )

        acl_table_group = sai_thrift_create_acl_table_group(
            self.client,
            acl_stage=SAI_ACL_STAGE_EGRESS,
            acl_bind_point_type_list=bp_list,
            type=SAI_ACL_TABLE_GROUP_TYPE_SEQUENTIAL,
        )
        self._assert_valid_oid(acl_table_group)

        acl_table = sai_thrift_create_acl_table(
            self.client,
            acl_stage=SAI_ACL_STAGE_EGRESS,
            acl_bind_point_type_list=bp_list,
            field_dst_ip=True,
        )
        self._assert_valid_oid(acl_table)

        member = sai_thrift_create_acl_table_group_member(
            self.client,
            acl_table_group_id=acl_table_group,
            acl_table_id=acl_table,
            priority=5,
        )
        self._assert_valid_oid(member)

        acl_entry = sai_thrift_create_acl_entry(
            self.client,
            table_id=acl_table,
            priority=5,
            field_dst_ip=sai_thrift_acl_field_data_t(
                enable=True,
                data=sai_thrift_acl_field_data_data_t(ip4="192.168.0.1"),
                mask=sai_thrift_acl_field_data_mask_t(ip4="255.255.255.0"),
            ),
            action_packet_action=sai_thrift_acl_action_data_t(
                enable=True,
                parameter=sai_thrift_acl_action_parameter_t(
                    s32=SAI_PACKET_ACTION_FORWARD
                ),
            ),
        )
        self._assert_valid_oid(acl_entry)

        acl_counter = sai_thrift_create_acl_counter(
            self.client, table_id=acl_table, enable_byte_count=True
        )
        self._assert_valid_oid(acl_counter)

        sai_thrift_remove_acl_counter(self.client, acl_counter)
        sai_thrift_remove_acl_entry(self.client, acl_entry)
        sai_thrift_remove_acl_table_group_member(self.client, member)
        sai_thrift_remove_acl_table(self.client, acl_table)
        self._assert_status_success(
            sai_thrift_remove_acl_table_group(self.client, acl_table_group),
            "final remove",
        )

    def test_acl_pipeline_with_range(self):
        """
        Build an ACL pipeline that uses an ACL range for L4 port matching.
        """
        acl_range = sai_thrift_create_acl_range(
            self.client,
            type=SAI_ACL_RANGE_TYPE_L4_SRC_PORT_RANGE,
            limit=sai_thrift_u32_range_t(min=1024, max=65535),
        )
        self._assert_valid_oid(acl_range, "create range")
        self._assert_status_success(adapter.status)

        acl_table = sai_thrift_create_acl_table(
            self.client,
            acl_stage=SAI_ACL_STAGE_INGRESS,
            field_acl_range_type=True,
        )
        self._assert_valid_oid(acl_table, "create table")
        self._assert_status_success(adapter.status)

        acl_entry = sai_thrift_create_acl_entry(
            self.client,
            table_id=acl_table,
            priority=1,
            field_acl_range_type=sai_thrift_acl_field_data_t(
                enable=True,
                data=sai_thrift_acl_field_data_data_t(
                    objlist=sai_thrift_object_list_t(count=1, idlist=[acl_range])
                ),
            ),
            action_packet_action=sai_thrift_acl_action_data_t(
                enable=True,
                parameter=sai_thrift_acl_action_parameter_t(
                    s32=SAI_PACKET_ACTION_DROP
                ),
            ),
        )
        self._assert_valid_oid(acl_entry, "create entry")
        self._assert_status_success(adapter.status)

        self._assert_status_success(
            sai_thrift_remove_acl_entry(self.client, acl_entry), "remove entry")
        self._assert_status_success(
            sai_thrift_remove_acl_table(self.client, acl_table), "remove table")
        self._assert_status_success(
            sai_thrift_remove_acl_range(self.client, acl_range), "remove range")

    def test_multiple_acl_entries_per_table(self):
        """
        Create multiple ACL entries in one table and verify all can be
        created and removed without errors.
        """
        acl_table = sai_thrift_create_acl_table(
            self.client, acl_stage=SAI_ACL_STAGE_INGRESS, field_src_ip=True
        )
        self._assert_valid_oid(acl_table)

        entries = []
        for i in range(1, 6):
            entry = sai_thrift_create_acl_entry(
                self.client,
                table_id=acl_table,
                priority=i,
                field_src_ip=sai_thrift_acl_field_data_t(
                    enable=True,
                    data=sai_thrift_acl_field_data_data_t(
                        ip4="10.0.{}.1".format(i)
                    ),
                    mask=sai_thrift_acl_field_data_mask_t(ip4="255.255.255.255"),
                ),
                action_packet_action=sai_thrift_acl_action_data_t(
                    enable=True,
                    parameter=sai_thrift_acl_action_parameter_t(
                        s32=SAI_PACKET_ACTION_DROP
                    ),
                ),
            )
            self._assert_valid_oid(entry, "create entry {}".format(i))
            self._assert_status_success(adapter.status)
            entries.append(entry)

        for i, entry in enumerate(reversed(entries), 1):
            self._assert_status_success(
                sai_thrift_remove_acl_entry(self.client, entry),
                "remove entry {}".format(i),
            )

        self._assert_status_success(
            sai_thrift_remove_acl_table(self.client, acl_table), "remove table"
        )


if __name__ == "__main__":
    unittest.main()
